### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by issour** [czemu/nova-calendar-tool#5]
Hi,
Thanks for your this tool !!!
it's possible to add optional recurring events ?
Many thanks

**Comment by czemu** [comment]
Hi,

Thanks for the kind words!

I like your idea, but unfortunately I can't add recurring events to this package due to lack of support for them in the [spatie/laravel-google-calendar](https://github.com/spatie/laravel-google-calendar) package which this package is based on. :(

> Limitations
The Google Calendar API provides many options. This package doesn't support all of them. For instance, recurring events cannot be managed properly with this package. (...)

Source: https://github.com/spatie/laravel-google-calendar#limitations

If they add support for the recurring events, I'll also try to add it.

**Comment by issour** [comment]
Hi,
Thanks you !!!
